const translations_en = {
  'tap-to-start': 'Tap or Hold to start',
  'time': 'Time',
  'add-select-rubik': 'Add / Select Rubik',
  'view-times': 'View Times',
  'settings': 'Settings',
  'inspection-timer': 'Inspection Timer (15s)',
  'session-management': 'Session Management',
  'save-unknown-solves': 'Save ??? Solves',
  'timer-display-duration': 'Timer Display Duration (ms)',
  'inspection-time': 'Inspection Time (s)',
  'language': 'Language',
  'import': 'Import',
  'export': 'Export',
  'cancel': 'Cancel',
  'cancel-timer': 'Cancel Timer',
  'confirm': 'Confirm',
  'close': 'Close',
  'add': 'Add',
  'remove': 'Remove',
  'rename': 'Rename',
  'delete': 'Delete',
  'all': 'All',
  'fastest': 'Fastest',
  'slowest': 'Slowest',
  'records': 'Records',
  'no-records': 'No records yet',
  'recent-solves': 'Recent Solves',
  'no-solves': 'No solves yet',
  'not-saved': 'Not saved (??? solve)',
  'new-record': '🎉 New Record! 🎉',
  'solve-saved': 'Solve saved',
  'no-times': 'No times recorded yet',
  'error-adding-cube': 'Error adding cube:',
  'confirm-remove': 'Remove',
  'error-removing-cube': 'Error removing cube:',
  'enter-new-name': 'Enter a new name.',
  'name-already-exists': 'Name already exists.',
  'error-renaming-cube': 'Error renaming cube:',
  'delete-all-times': 'Delete ALL solve times?',
  'clear-all-records': 'Clear all records?',
  'select-rubik': 'Select Rubik',
  'add-new-rubik': 'Add New Rubik',
  'rename-selected': 'Rename Selected',
  'filter-by-rubik': 'Filter by Rubik:',
  'sort-by': 'Sort by:',
  'last': 'Last',
  'first': 'First',
  'all-solve-times': 'All Solve Times',
  'rubik': 'Rubik',
  'change-type': 'Change Type',
  'action': 'Action',
  'clear-all-times': 'Clear All Times',
  'clear-records': 'Clear Records',
  'reset-settings': 'Reset Settings',
  'inspection-delay': 'Inspection Delay (ms)',
  'settings-title': 'Settings',
  'import-export-title': 'Import / Export',
  'copy-to-clipboard': 'Copy to Clipboard',
  'save-to-file': 'Save to File',
  'file-operation-title': 'File Operation',
  'save-settings': 'Save Settings',
  'confirm-reset-settings': 'Are you sure you want to reset all settings to default?',
  'data-copied-to-clipboard': 'Data copied to clipboard',
  'error-copying-to-clipboard': 'Error copying to clipboard',
  'settings-only': 'Settings Only',
  'times-only': 'Times Only',
  'both-settings-and-times': 'Both Settings and Times',
  'cube-added-successfully': 'Cube added successfully!',
  // Added missing translations
  'solve-not-saved-unknown': 'Solve not saved (unknown cube type)',
  'pending-solve-saved': 'Pending ??? solve saved',
  'error-saving-solve': 'Error saving solve',
  'inspection-running': 'Inspection Running...',
  // Multilingual cube name translations
  'add-multilingual-cube': 'Add Multilingual Cube',
  'base-cube-name': 'Base Cube Name',
  'english-name': 'English Name',
  'enter-persian-name': 'Enter Persian Name',
  'enter-all-names': 'Please enter all required names',
  'create-multilingual-cube': 'Create Multilingual Cube',
  'multilingual-name-added': 'Multilingual cube created successfully!',
  'error-adding-multilingual-name': 'Error creating multilingual cube'
};