name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev libssl-dev libjpeg-dev libpng-dev libsqlite3-dev
        sudo apt install -y liblzma-dev libbz2-dev libreadline-dev libsqlite3-dev
        sudo apt install -y zlib1g-dev libncurses5-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install cython

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Android SDK
      run: |
        sudo apt install -y android-sdk
        echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV

    - name: Install Buildozer
      run: |
        pip install buildozer
        # Initialize buildozer if needed
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK with detailed logging
      run: |
        # Create bin directory if it doesn't exist
        mkdir -p bin
        
        # Build with verbose output
        buildozer -v android debug
        
        # List contents of bin directory to verify APK creation
        echo "Contents of bin directory:"
        ls -la bin/ || echo "Bin directory not found or empty"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rubik-timer-apk
        path: bin/*.apk
        if-no-files-found: ignore

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.create_release.outputs.upload_url != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/*.apk
        asset_name: rubik-timer.apk
        asset_content_type: application/vnd.android.package-archive